force-app/main/default/objects/auara_DailyCommitment__c/auara_DailyCommitment__c.object-meta.xml
<CustomObject>
    <label>Daily Commitment</label>
    <nameField>
        <displayFormat>DCM-{000000}</displayFormat>
        <label>Daily Commitment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Commitments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/auara_DailyCommitment__c/fields/auara_CommitmentDate__c.field-meta.xml
<CustomField>
    <fullName>auara_CommitmentDate__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Commitment Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/Auara_TestCommitmentCounterCtrl.cls
@isTest
public class Auara_TestCommitmentCounterCtrl {

    @TestSetup static void loadData(){
        Set <Id> idDaily = Auara_TestFactory.createDailyCommitments(1);
    }
   @isTest static void testCommitmentCounter(){
    List <auara_DailyCommitment__c> idDailyComms = [SELECT Id, auara_CommitmentDate__c FROM auara_DailyCommitment__c];
       Test.startTest();
       auara_DailyCommitment__c myDailyComm1 = Auara_CommitmentCounterCtrl.setDailyCommitment(idDailyComms[0]);
       System.assertEquals(myDailyComm1.Id, idDailyComms[0].Id);
       auara_DailyCommitment__c myDailyComm2 = Auara_CommitmentCounterCtrl.getDailyCommitment(System.now());
       System.assertEquals(myDailyComm2.Id, idDailyComms[0].Id);
       Test.stopTest();
   }
}