force-app/main/default/objects/auara_DailyCommitment__c/auara_DailyCommitment__c.object-meta.xml
<CustomObject>
    <label>Daily Commitment</label>
    <nameField>
        <displayFormat>DCM-{000000}</displayFormat>
        <label>Daily Commitment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Commitments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/auara_DailyCommitment__c/fields/auara_CommitmentDate__c.field-meta.xml
<CustomField>
    <fullName>auara_CommitmentDate__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Commitment Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/Auara_DailyCommitmentsSelector.cls
global with sharing class Auara_DailyCommitmentsSelector extends fflib_SObjectSelector implements Auara_DailyCommitmentsSelectorI {

    public static Auara_DailyCommitmentsSelectorI newInstance(){
        return (Auara_DailyCommitmentsSelectorI) Auara_Application.SELECTOR.newInstance(auara_DailyCommitment__c.SObjectType);
    }

    /**
      * Default constructor. Reads the fields from the getSObjectFieldList() method
      **/
    global Auara_DailyCommitmentsSelector(){
        super(false);
    }

    /**
      * Constructor that allows a parameter to use FieldSets if True
      **/
    public Auara_DailyCommitmentsSelector(Boolean includeFieldSetFields){
        super(includeFieldSetFields);
        this.setDefaultFieldSet(Auara_Application.DEFAULTFIELDSET);
    }

    /**
      * Constructor that allows a parameter to use the selected fieldsets
      **/
    public Auara_DailyCommitmentsSelector(List <String> fieldSetList){
        super(true);
        this.setFieldSetList(fieldSetList);
    }

    /**
      * Returns a default list of fields if FieldSets functionality is not used (No Dependency Injection Pattern here!)
      **/
    public override List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField> {
                   auara_DailyCommitment__c.Id,
                   auara_DailyCommitment__c.Name
        };
    }

    public override Schema.SObjectType getSObjectType(){
        return auara_DailyCommitment__c.sObjectType;
    }

    global List<auara_DailyCommitment__c> selectById(Set<ID> idSet){
        return (List<auara_DailyCommitment__c>) selectSObjectsById(idSet);
    }

    global List<auara_DailyCommitment__c> selectByDate(Date selectedDate){
        fflib_QueryFactory commitmentsQF = newQueryFactory();
        return (List<auara_DailyCommitment__c>) Database.query(
      commitmentsQF.setCondition('auara_CommitmentDate__c = :selectedDate').toSOQL());

    }

}