force-app/main/default/objects/auara_DailyCommitment__c/auara_DailyCommitment__c.object-meta.xml
<CustomObject>
    <label>Daily Commitment</label>
    <nameField>
        <displayFormat>DCM-{000000}</displayFormat>
        <label>Daily Commitment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Commitments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/auara_DailyCommitment__c/fields/auara_id__c.field-meta.xml
<CustomField>
    <fullName>auara_id__c</fullName>
    <externalId>true</externalId>
    <label>Auara Id</label>
    <length>15</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/Auara_UOWUpsertCommitment.cls
public with sharing class Auara_UOWUpsertCommitment implements fflib_SObjectUnitOfWork.IDoWork {

    public Database.UpsertResult[] results {
        get;
        private set;
    }

    private List<auara_DailyCommitment__c> mRecords;

    public Auara_UOWUpsertCommitment(){
        mRecords = new List<auara_DailyCommitment__c>();
    }

    public void registerCommitmentUpsert(auara_DailyCommitment__c record){
        mRecords.add(record);
    }

    public void doWork(){
        Schema.SObjectField keyField = auara_DailyCommitment__c.Fields.auara_id__c;
        results = Database.upsert(mRecords, keyField, false);
    }

}