force-app/main/default/objects/auara_DailyCommitment__c/auara_DailyCommitment__c.object-meta.xml
<CustomObject>
    <label>Daily Commitment</label>
    <nameField>
        <displayFormat>DCM-{000000}</displayFormat>
        <label>Daily Commitment Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Daily Commitments</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/auara_DailyCommitment__c/fields/auara_CommitmentDate__c.field-meta.xml
<CustomField>
    <fullName>auara_CommitmentDate__c</fullName>
    <defaultValue>TODAY()</defaultValue>
    <label>Commitment Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/Auara_CommitmentCounterCtrl.cls
public inherited sharing class Auara_CommitmentCounterCtrl {
    @AuraEnabled
    public static auara_DailyCommitment__c getDailyCommitment(Datetime selectedDate){
        auara_DailyCommitment__c resultado;
        List<auara_DailyCommitment__c> listCommitment = new Auara_DailyCommitmentsSelector(true).SelectByDate(selectedDate.date());
        if(listCommitment != null && !listCommitment.isEmpty()) {
            resultado = listCommitment[0];
        }
        return resultado;
    }

    @AuraEnabled
    public static auara_DailyCommitment__c setDailyCommitment(auara_DailyCommitment__c myCommitment){
        auara_DailyCommitment__c resultado;
        Date dateValue = date.newinstance(myCommitment.auara_CommitmentDate__c.year(), myCommitment.auara_CommitmentDate__c.month(), myCommitment.auara_CommitmentDate__c.day());
        myCommitment.auara_RecordKey__c = dateValue + UserInfo.getUserId();
        List<auara_DailyCommitment__c> listCommitment = new Auara_DailyCommitments(new List<auara_DailyCommitment__c> {myCommitment}).upsertCommitment();
        if(listCommitment != null && !listCommitment.isEmpty()) {
            resultado = listCommitment[0];
        }
        return resultado;
    }
}