force-app/main/default/objects/Opportunity/fields/auara_BillingCity__c.field-meta.xml
<CustomField>
    <fullName>auara_BillingCity__c</fullName>
    <label>Billing City</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/auara_BillingCountry__c.field-meta.xml
<CustomField>
    <fullName>auara_BillingCountry__c</fullName>
    <label>Billing Country</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/auara_BillingStateProvince__c.field-meta.xml
<CustomField>
    <fullName>auara_BillingStateProvince__c</fullName>
    <label>Billing State/Province</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/auara_BillingStreet__c.field-meta.xml
<CustomField>
    <fullName>auara_BillingStreet__c</fullName>
    <label>Billing Street</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/auara_BillingZipPostalCode__c.field-meta.xml
<CustomField>
    <fullName>auara_BillingZipPostalCode__c</fullName>
    <label>Billing Zip/Postal Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/Auara_OpportunitiesHelper.cls
public with sharing class Auara_OpportunitiesHelper {
  public void applyDefaults(List <opportunity> records){

    // Get the List of Accounts  associated to the Opportunitys to process
    set<id> setLookup = new set<id>();
    for(opportunity myOpp : records) {
        if(myOpp.AccountId != null) {
            setLookup.add(myOpp.AccountId);
        }
    }

    // Get the Record details for each of the Account records by using the selector
    List <Account> accounts = new Auara_AccountsSelector(true).selectById(setlookup);

    // Construct a map with Id and record object of the Accounts, for reference later
    Map <Id, Account> mapAccounts = new Map<id, Account>();
    for(Account myAccount : accounts) {
        mapAccounts.put(myAccount.Id, myAccount);
    }

    // update each Opportunity with its corresponding Account record values using the map
    for(opportunity myOpp : records) {
        if(mapAccounts.containsKey(myOpp.AccountId)) {
            myOpp.auara_BillingCity__c = mapAccounts.get(myOpp.AccountId).BillingCity;
            myOpp.auara_BillingCountry__c = mapAccounts.get(myOpp.AccountId).BillingCountry;
            myOpp.auara_BillingStateProvince__c = mapAccounts.get(myOpp.AccountId).BillingState;
            myOpp.auara_BillingStreet__c = mapAccounts.get(myOpp.AccountId).BillingStreet;
            myOpp.auara_BillingZipPostalCode__c = mapAccounts.get(myOpp.AccountId).BillingPostalCode;
        }
    }
}
}